# Generated by Django 4.2.1 on 2023-06-02 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='googl_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 6, 2)),
        ),
    ]
