# Generated by Django 4.2.1 on 2023-06-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books_googl_id_alter_rentsbook_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
