# Generated by Django 4.2.1 on 2023-06-06 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_library_user_alter_rentsbook_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
    ]
