# Generated by Django 4.2.1 on 2023-06-29 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_rentsbook_start_date_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='rent_user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='book_renter', to='main.userprofile'),
        ),
    ]
