# Generated by Django 4.2.1 on 2023-07-06 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_message_owner_alter_message_rent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='rent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_renter', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 7, 6)),
        ),
    ]
