# Generated by Django 4.2.1 on 2023-07-07 21:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_message_sender_alter_message_rent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentsbook',
            name='book',
            field=models.ForeignKey(default=54, on_delete=django.db.models.deletion.CASCADE, to='main.library'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 7, 8)),
        ),
    ]
