# Generated by Django 4.2.1 on 2023-07-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_rentsbook_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='rent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.userprofile'),
        ),
    ]
