# Generated by Django 4.2.1 on 2023-07-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_rentsbook_rent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentsbook',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentsbook',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
